version: '3'

services:
  redisearch:
    image: redislabs/redisearch:latest
    restart: always
    command: [
      "redis-server",
      "--loadmodule",
      "/usr/lib/redis/modules/redisearch.so",
      "TIMEOUT", "100",         # query timeout
      "ON_TIMEOUT", "RETURN",   # return results found on timeout
      "MINPREFIX", "1",         # Ensure that prefix search is always performed
      "MAXEXPANSIONS", "1000",  # Increase the number of expansions for query prefixes
    ]

  api_redisearch:
    image: api_redisearch
    container_name: api_redisearch
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8100:80
    volumes:
      - ./api.conf:/etc/nginx/sites-available/default
      - ./api:/var/www/html/api
      - ./scripts:/var/www/html/scripts
    depends_on:
      - redisearch
    command: ./scripts/init.sh
    restart: always
