version: '3'

services:
  redisearch:
    image: redislabs/redisearch:latest
    restart: always

  api_redisearch:
    image: api_redisearch
    container_name: api_redisearch
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8100:80
    volumes:
      - ./api.conf:/etc/nginx/sites-available/default
      - ./api:/var/www/html/api
      - ./scripts:/var/www/html/scripts
    depends_on:
      - redisearch
    # command: tail -f /dev/null
    restart: always
